services:
  postgres:
    image: postgres:16
    container_name: finanzas_postgres
    restart: always
    environment:
      POSTGRES_USER: finanzas_user
      POSTGRES_PASSWORD: finanzas_pass
      POSTGRES_DB: finanzas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: